version: "3.9"

networks:
  testing:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php
      - mysql
    networks:
      - testing

  php:
    build:
      args:
        user: dummy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - testing

  mysql:
    image: mysql:8
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - testing

  redis:
    image: redis:6
    container_name: ${APP_NAME}-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    networks:
      - testing
